# Generated by Django 4.0.1 on 2022-02-21 08:46

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'required': 'Not Valid Egyptian Phone Number'}, max_length=11, null=True, unique=True, validators=[users.models.validate_egyptian_number]),
        ),
    ]
